version: "2"

linters:
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gocognit
    - gocritic
    - govet
    - ineffassign
    - nilerr
    - staticcheck
    - unconvert
    - unparam
    - unused
